version: "3"
services:
  db:
    container_name: mysql-8.0
    image: mysql:8.0
    ports:
      - "3306:3306"
    command:
      - --default_authentication_plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    volumes:
      - db_data:/var/lib/mysql
    networks:
      my-net:
        ipv4_address: 172.18.0.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:

  php-7.4:
    container_name: php-7.4
    build: ./php-7.4/.
    ports:
      - "9000:9000"
    networks:
      my-net:
        ipv4_address: 172.18.0.2
    volumes:
      - wordpress:/var/www/html
    restart: always


  my-wordpress:
    container_name: my-wordpress
    depends_on:
      - php-7.4
      - mysql-8.0
    build: ./my-wordpress/.
    ports:
      - "80:80"
    networks:
      my-net:
        ipv4_address: 172.18.0.3
    volumes:
      - wordpress:/var/www/html
    restart: always
    environment:
      SERVER_NAME:
      LEGO_SECRET_ID:
      LEGO_SECRET_KEY:
      LEGO_EMAIL:

networks:
  my-net:
    ipam:
      config:
      - subnet: 172.18.0.0/24
        gateway: 172.18.0.1

volumes:
  wordpress: 
  db_data: