
FROM ubuntu:22.04

WORKDIR /var/www/html

RUN   set -x;  apt-get update && apt-get -y install wget && wget https://wordpress.org/latest.tar.gz && \
      tar -xzvf latest.tar.gz && rm latest.tar.gz

FROM nginx:stable

LABEL maintainer="mysens@126.com"

WORKDIR /var/www/html 

# ENV SERVER_NAME localhost

COPY --from=0 /var/www/html .

COPY nginx.conf /etc/nginx

COPY default.conf /etc/nginx/conf.d

RUN sed -i '5 i sed -i "s/SERVER_NAME/$SERVER_NAME/" /etc/nginx/conf.d/default.conf' /docker-entrypoint.sh